version: '3'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - laravel
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - "8080:80"
        depends_on:
            - php
        networks:
            - laravel
    mysql:
        image: mysql:latest
        platform: linux/amd64
        environment:
            MYSQL_DATABASE: test_task
            MYSQL_USER: root1
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - laravel

networks:
    laravel:
